const messagesEl = document.getElementById("messages");
const composerEl = document.getElementById("composer");
const promptEl = document.getElementById("prompt");
const sendEl = document.getElementById("send");
const newChatEl = document.getElementById("new-chat");
const modelNameEl = document.getElementById("model-name");

let systemPrompt = "You are a helpful assistant.";
let conversation = [];

function renderEmptyState() {
  messagesEl.innerHTML = `
    <div class="empty-state">
      <h2>Start a conversation</h2>
      <p>Messages are generated by your Heretic model running on Railway.</p>
    </div>
  `;
}

function renderMessages() {
  if (conversation.length === 0) {
    renderEmptyState();
    return;
  }

  messagesEl.innerHTML = conversation
    .map(
      (message) => `
        <article class="message ${message.role}">
          <div class="message-role">${message.role}</div>
          <div class="message-content">${escapeHtml(message.content)}</div>
        </article>
      `,
    )
    .join("");

  messagesEl.scrollTop = messagesEl.scrollHeight;
}

function escapeHtml(value) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

function setBusy(isBusy) {
  sendEl.disabled = isBusy;
  promptEl.disabled = isBusy;
}

async function loadConfig() {
  const response = await fetch("/api/config");
  if (!response.ok) {
    throw new Error("Failed to load server config");
  }

  const config = await response.json();
  systemPrompt = config.system_prompt;
  modelNameEl.textContent = config.model;
}

async function streamAssistantReply(messages) {
  const response = await fetch("/api/chat/stream", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ messages }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(errorText || "Generation failed");
  }

  const assistantMessage = { role: "assistant", content: "" };
  conversation.push(assistantMessage);
  renderMessages();

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";

  while (true) {
    const { value, done } = await reader.read();
    if (done) {
      break;
    }

    buffer += decoder.decode(value, { stream: true });
    const events = buffer.split("\n\n");
    buffer = events.pop() ?? "";

    for (const event of events) {
      const dataLine = event
        .split("\n")
        .find((line) => line.startsWith("data: "));

      if (!dataLine) {
        continue;
      }

      const payload = dataLine.slice(6);
      if (payload === "[DONE]") {
        return;
      }

      const parsed = JSON.parse(payload);
      if (parsed.error) {
        throw new Error(parsed.error);
      }

      assistantMessage.content += parsed.content;
      renderMessages();
    }
  }
}

composerEl.addEventListener("submit", async (event) => {
  event.preventDefault();

  const content = promptEl.value.trim();
  if (!content) {
    return;
  }

  promptEl.value = "";
  setBusy(true);

  conversation.push({ role: "user", content });
  renderMessages();

  const messages = [
    { role: "system", content: systemPrompt },
    ...conversation,
  ];

  try {
    await streamAssistantReply(messages);
  } catch (error) {
    conversation.push({
      role: "error",
      content: error instanceof Error ? error.message : "Unknown error",
    });
    renderMessages();
  } finally {
    setBusy(false);
    promptEl.focus();
  }
});

newChatEl.addEventListener("click", () => {
  conversation = [];
  renderEmptyState();
  promptEl.focus();
});

promptEl.addEventListener("keydown", (event) => {
  if (event.key === "Enter" && !event.shiftKey) {
    event.preventDefault();
    composerEl.requestSubmit();
  }
});

renderEmptyState();

loadConfig().catch((error) => {
  modelNameEl.textContent = error.message;
});
